---
name: 'app-service-configurable'
version: '1.2.0'
releaseName: 'geneva'
releaseStream: '1.2.0'
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
gitTag: false
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/docker-app-service-configurable
      - docker.io/edgexfoundry/docker-app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/docker-app-service-configurable-arm64
      - docker.io/edgexfoundry/docker-app-service-configurable-arm64
snap: false
snapChannels:
  - channel: 'latest/beta'
  - channel: 'latest/candidate'